
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baywatch-prod-worker-deployment
  labels:
    app: baywatch-prod-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baywatch-prod-worker
  template:
    metadata:
      labels:
        app: baywatch-prod-worker
    spec:
      containers:
        - name: baywatch-prod-worker
          imagePullPolicy: Always
          image: aravp4/baywatch_api:0.1.0
          command: ["uv", "run", "--", "python", "worker.py"]
          env:
          - name: REDIS_IP
            value: baywatch-prod-redis-service
          - name: LOG_LEVEL
            value: INFO